[project]
name = "flask-sandbox"
version = "1.0.0"
dependencies = [
    "Flask",
    "dotenv-cli",
    "gunicorn",
    "uvicorn",
    "turbo-flask",
    "ruff",
    "black",
]

[tool.black]
line-length = 80